### ISSUE TITLE
RSTManager.gd (and other "scr" scripts) don't extend to Control.gd

### ISSUE THREAD

**Issue by DeerTears** [nonunknown/integrated-docs#1]
Upon opening Control.gd (as suggested in Readme.md) this happened:

![image](https://user-images.githubusercontent.com/47726614/78511359-4d3f2500-7759-11ea-9adf-452508341f2f.png)

I think this happened because Github replaced your "_" with a "-" because Github doesn't like to use underscores or spaces in repository names. You can fix this by renaming everything to use "-" or to replace all instances of the name with "IntegratedDocs" instead.

Also, while we're on the topic of names I think you meant to type "src" - which stands for Source. I've made the same mistake before, I just figured it was worth pointing out during this early point of development.

I'm really excited to see where this project goes. Please let me know if you'd like to know more about how I tried to open/use this plugin.

**Comment by nonunknown** [comment]
About the _ and - Yes it was a pain in the ass to bring the files to this repo.

About the "src" which means Source I did not made any mistak my intention was "scr" (Script)

Yeah any information/help/improvement is very welcome.
